# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/15774/lab202/lab202.srcs/sources_1/ip/blk_mem_gen_1_RF/blk_mem_gen_1_RF.xci
# IP: The module: 'blk_mem_gen_1_RF' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/15774/lab202/lab202.gen/sources_1/ip/blk_mem_gen_1_RF/blk_mem_gen_1_RF_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_1_RF'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/15774/lab202/lab202.srcs/sources_1/ip/blk_mem_gen_1_RF/blk_mem_gen_1_RF.xci
# IP: The module: 'blk_mem_gen_1_RF' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/15774/lab202/lab202.gen/sources_1/ip/blk_mem_gen_1_RF/blk_mem_gen_1_RF_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_1_RF'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
